models.py
# imports 
from app import db
import re
from datetime import datetime
from time import time
from flask_security import UserMixin, RoleMixin

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)

posts_tags = db.Table(
    'posts_tags',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')), 
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
)

roles_users = db.Table(
    'roles_users', 
    db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer, db.ForeignKey('role.id'))
)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    create = db.Column(db.DateTime, default=datetime.now())
    tags = db.relationship('Tag', secondary=posts_tags, backref=db.backref('posts'), lazy='dynamic')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_slug()
        
    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        else:
            self.slug = str(int(time()))
            
    def __repr__(self):
        return f'<Post id: {self.id}, title: {self.title}>'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.slug = slugify(self.title)
        
    def __repr__(self):
        return f'<Tag id: {self.id}, title: {self.title}>'


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean)
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users'), lazy='dynamic')


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)

posts_bp/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')
    

app.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from config import Config
from flask_security import SQLAlchemySessionUserDatastore, Security, SQLAlchemyUserDatastore

# app config
app = Flask(__name__)
app.config.from_object(Config)

# db init
db = SQLAlchemy(app)

# import late due to circular error
from models import *

# migration init
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

# admin config
admin = Admin(app)
admin.add_view(ModelView(Post, db.session))
admin.add_view(ModelView(Tag, db.session))

# flask security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

@app.errorhandler(404)
def page_not_found(event):
    return render_template('404.html'), 404

main.py
from app import *
from posts_bp.blueprint import *

app.register_blueprint(posts, url_prefix='/blog')    

if __name__ == "__main__":
    app.run(port=5000)

posts_bp/blueprint.py
from flask import (Blueprint,
    render_template, request, url_for, redirect)
from .forms import PostForm
# from flask_security import login_required
from app import db
from models import *

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/create', methods=["POST", "GET"])
def post_create():
    form = PostForm()
    
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')
        
        try: 
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Didnt create post')
            
        return redirect(url_for('posts.post_detail', slug=post.slug))
            
    return render_template('posts/post_create.html', form=form) 


# localhost:5000/blog/
@posts.route('/', methods=['GET'])
def posts_lst():
    q = request.args.get('q')
    
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.create.desc())
        
    page = request.args.get('page') 
    
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
        
    pages = posts.paginate(page=page, per_page=1)
        
    return render_template('posts/posts.html', posts=posts, pages=pages)


# localhost:5000/blog/first-post/
@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    return render_template('posts/post_detail.html', post=post)


@posts.route('/tags/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    return render_template('posts/tag_detail.html', tag=tag)

@posts.route('/<slug>/edit', methods=["POST", "GET"])
def post_update(slug):
    post = Post.query.filter(Post.slug==slug).first()
    
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))
    
    form = PostForm(obj=post)
    
    return render_template('posts/edit.html', post=post, form=form)

posts_bp/templates/posts/edit.html
{% extends 'main.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content %}
    <h1> Edit: {{ post.title }}</h1>
    <form action="{{ url_for('posts.post_update', slug=post.slug) }}" method="POST">
        {% for field in form %}
            <div class="form-group mb-5">
                {{ field.label() }}
                {{ field(class="form-control mb-5") }}
            </div>
        {% endfor %}
        <button class="btn btn-primary mb-5">Publish</button>
    </form>
{% endblock %}

posts_bp/templates/posts/includes/card.html
<div class="card text-white bg-primary mb-4" style="max-width: 18rem;">
    <div class="card-header">{{ post.create.date() }}</div>
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}"><span class="badge badge-info"><h4>{{ post.title }}</h4></span></a>
        </h5>
        <p class="card-text">{{ post.body }}</p>
        <a href="{{ url_for('posts.post_detail', slug=post.slug) }}" class="btn btn-primary"><button type="button"
                class="btn btn-light">Details</button></a>
    </div>
    {% if post.tags.count() %}
    <div class="card-footer text-muted">
        {% for tag in post.tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
                <span class="badge badge-info">{{ tag.title }}</span>
            </a>
        {% endfor %}
    </div>
    {% endif %}
</div>

posts_bp/templates/posts/post_create.html
{% extends 'main.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content %}
    <h1>Create new post</h1>
    <form action="{{ url_for('posts.post_create') }}" method="POST">
        {% for field in form %}
            <div class="form-group mb-5">
                {{ field.label() }}
                {{ field(class="form-control mb-5") }}
            </div>
        {% endfor %}
        <button class="btn btn-primary mb-5">Publish</button>
    </form>
{% endblock %}

posts_bp/templates/posts/post_detail.html
{% extends 'main.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title}}</h1>
    <div class="">
        {{ post.body }}
    </div>
{% endblock %}

posts_bp/templates/posts/posts.html
{% extends 'main.html' %}

{% block title %}Feed{% endblock %}

{% block content %}

    {% for post in pages.items %}
        {% include 'posts/includes/card.html' %}
    {% endfor %}

    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item {% if not pages.has_prev %}
            disabled {% endif %}">
                <a class="page-link" href="./?page={{ 
                    pages.prev_num }}">Previous</a>
            </li>
            
            {% for page in pages.iter_pages() %}
                <li class="page-item {% if page == pages.page %} active {% endif %}">
                    <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
                </li>
            {% endfor %}

            <li class="page-item {% if not pages.has_next %}
            disabled {% endif %}">
                <a class="page-link" href="./?page={{
                    pages.next_num }}">Next</a>
            </li>
        </ul>
    </nav>

{% endblock %}

posts_bp/templates/posts/tag_detail.html
{% extends 'main.html' %}

{% block title %}
    Posts with "{{ tag.title }}" tag
{% endblock %}

{% block content %}
    <h1>Posts with "{{ tag.title }}" tag</h1>
    {% for post in tag.posts %}
        {% include 'posts/includes/card.html' %}
    {% endfor %}
{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary mb-5">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="navbar-brand" aria-current="page" href="{{ url_for('posts.posts_lst') }}">Feed</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" aria-current="page" href="{{ url_for('posts.post_create') }}">+ Post</a>
                    </li>
                </ul>
            </div>
                <form class="d-flex" method="GET">
                    <input class="form-control me-2" type="search" placeholder="Search" name="q">
                    <button class="btn btn-dark" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>